# Imagen base mínima
FROM ubuntu:22.04

# Variables para no preguntar durante instalaciones
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar e instalar dependencias de compilación y Python
RUN apt-get update && apt-get install -y \
    gfortran \
    gcc \
    make \
    wget \
    build-essential \
    libcfitsio-dev \
    python3.11 \
    python3-pip \
    git \
    && apt-get clean

# Forzamos python 3.11 (NO funciona sin esto)
FROM python:3.11-slim 

# Crear carpeta de trabajo
WORKDIR /opt/daophot

# Copiar todo el contenido del proyecto al contenedor
COPY ./photfun/daophot_wrap/daophot /opt/daophot
RUN cp /opt/daophot/lib/libgfortran.so.3 /usr/local/lib/.

# # Actualizar pip
# RUN pip install --upgrade pip
# # Instalar Photfun
# RUN pip install .

# COMPILAR DAOPHOT
# Primero compilar CFITSIO
WORKDIR /opt/daophot/src/cfitsio

# Dar permisos de ejecución al script configure
RUN chmod +x configure

# Instalar gcc, gfortran y make si no están presentes
RUN apt-get update && apt-get install -y gcc gfortran make

# Ejecutar el script configure, hacer make y make install
RUN ./configure --prefix=/usr/local && make

# Modificar Makefile para usar gfortran correctamente y agregar opciones de depuración
# WORKDIR /opt/photfun/daophot/src/daophot4
# RUN make daophot && \
#     make allstar && \
#     make daomatch && \
#     # make daomaster && \
#     make montage2 && \
#     make allframe && \
#     make daogrow

# Luego compilar DAOPHOT y amigos
WORKDIR /opt/daophot/bin
RUN chmod a+x daophot allstar daomatch daomaster montage2 allframe daogrow 

# Poner DAOPHOT y demás en el PATH
ENV PATH="/opt/daophot/bin:${PATH}"

# Directorio de trabajo final
WORKDIR /opt/daophot

# # Comando por defecto
CMD ["bash"]
